export const PROPERTY_TYPES = [
  { value: "casa", label: "Casa" },
  { value: "departamento", label: "Departamento" },
  { value: "local", label: "Local Comercial" },
  { value: "terreno", label: "Terreno" },
  { value: "oficina", label: "Oficina" },
  { value: "ph", label: "PH" },
  { value: "quinta", label: "Quinta" },
];

export const OPERATION_TYPES = [
  { value: "venta", label: "Venta" },
  { value: "alquiler", label: "Alquiler" },
];

export const PROPERTY_STATES = [
  { value: "disponible", label: "Disponible" },
  { value: "reservada", label: "Reservada" },
  { value: "vendida", label: "Vendida" },
  { value: "alquilada", label: "Alquilada" },
];

export const CURRENCIES = [
  { value: "ARS", label: "Pesos (ARS)" },
  { value: "USD", label: "Dólares (USD)" },
];

export const PROVINCES = [
  "Buenos Aires",
  "Catamarca",
  "Chaco",
  "Chubut",
  "Córdoba",
  "Corrientes",
  "Entre Ríos",
  "Formosa",
  "Jujuy",
  "La Pampa",
  "La Rioja",
  "Mendoza",
  "Misiones",
  "Neuquén",
  "Río Negro",
  "Salta",
  "San Juan",
  "San Luis",
  "Santa Cruz",
  "Santa Fe",
  "Santiago del Estero",
  "Tierra del Fuego",
  "Tucumán",
];

export const LOCALIDADES_POR_PROVINCIA: Record<string, string[]> = {
  Mendoza: [
    // Gran Mendoza
    "Capital (Mendoza)",
    "Godoy Cruz",
    "Guaymallén",
    "Las Heras",
    "Luján de Cuyo",
    "Maipú",
    "Lavalle",
    // Zona Este
    "San Martín",
    "Junín",
    "Rivadavia",
    "Santa Rosa",
    "La Paz",
    // Valle de Uco
    "Tunuyán",
    "Tupungato",
    "San Carlos",
    // Zona Sur
    "San Rafael",
    "General Alvear",
    "Malargüe",
  ],
  "Buenos Aires": [
    "La Plata",
    "Mar del Plata",
    "Bahía Blanca",
    "Quilmes",
    "Lanús",
    "Lomas de Zamora",
    "Almirante Brown",
    "Berazategui",
    "Florencio Varela",
    "San Isidro",
    "Vicente López",
    "San Martín",
    "Tres de Febrero",
    "Morón",
    "Ituzaingó",
    "Hurlingham",
    "Merlo",
    "Moreno",
    "General Rodríguez",
    "Luján",
    "Campana",
    "Zárate",
    "San Nicolás",
    "Tandil",
    "Olavarría",
    "Azul",
    "Necochea",
    "Pergamino",
    "Junín",
    "Pilar",
    "Tigre",
    "San Fernando",
    "Escobar",
    "Ezeiza",
    "Cañuelas",
  ],
  "Ciudad Autónoma de Buenos Aires": [
    "Palermo",
    "Recoleta",
    "Belgrano",
    "Caballito",
    "Flores",
    "Villa Urquiza",
    "Almagro",
    "Boedo",
    "San Telmo",
    "La Boca",
    "Barracas",
    "Villa del Parque",
    "Devoto",
    "Saavedra",
    "Núñez",
    "Colegiales",
    "Chacarita",
    "Villa Crespo",
    "Balvanera",
    "Monserrat",
    "Retiro",
    "Puerto Madero",
    "Liniers",
    "Mataderos",
    "Villa Lugano",
    "Villa Riachuelo",
  ],
  Córdoba: [
    "Córdoba Capital",
    "Villa Carlos Paz",
    "Río Cuarto",
    "San Francisco",
    "Villa María",
    "Río Tercero",
    "Cosquín",
    "La Falda",
    "Alta Gracia",
    "Bell Ville",
    "Marcos Juárez",
    "Cruz del Eje",
    "Deán Funes",
    "Villa del Rosario",
    "Laboulaye",
    "Río Segundo",
  ],
  "Santa Fe": [
    "Rosario",
    "Santa Fe Capital",
    "Rafaela",
    "Venado Tuerto",
    "Reconquista",
    "San Lorenzo",
    "Casilda",
    "Cañada de Gómez",
    "Firmat",
    "Villa Constitución",
    "Esperanza",
    "Santo Tomé",
    "Pérez",
  ],
  Tucumán: [
    "San Miguel de Tucumán",
    "Tafí Viejo",
    "Yerba Buena",
    "Banda del Río Salí",
    "Aguilares",
    "Concepción",
    "Monteros",
    "Famaillá",
  ],
  Salta: [
    "Salta Capital",
    "San Ramón de la Nueva Orán",
    "Tartagal",
    "General José de San Martín",
    "Güemes",
    "Cafayate",
    "Rosario de la Frontera",
  ],
  Neuquén: [
    "Neuquén Capital",
    "Centenario",
    "Plottier",
    "Cutral Có",
    "Plaza Huincul",
    "San Martín de los Andes",
    "Zapala",
    "Junín de los Andes",
  ],
  "Río Negro": [
    "Viedma",
    "Bariloche",
    "General Roca",
    "Cipolletti",
    "Allen",
    "El Bolsón",
    "Villa Regina",
    "Lamarque",
  ],
  Chaco: [
    "Resistencia",
    "Barranqueras",
    "Fontana",
    "Presidencia Roque Sáenz Peña",
    "Villa Ángela",
    "Charata",
  ],
  Misiones: [
    "Posadas",
    "Oberá",
    "Eldorado",
    "Puerto Iguazú",
    "Apóstoles",
    "Leandro N. Alem",
  ],
  "Entre Ríos": [
    "Paraná",
    "Concordia",
    "Gualeguaychú",
    "Concepción del Uruguay",
    "Colón",
    "Victoria",
    "Villaguay",
  ],
  Corrientes: [
    "Corrientes Capital",
    "Goya",
    "Paso de los Libres",
    "Curuzú Cuatiá",
    "Mercedes",
    "Esquina",
  ],
  Jujuy: [
    "San Salvador de Jujuy",
    "Palpalá",
    "San Pedro",
    "Libertador General San Martín",
    "Humahuaca",
    "Tilcara",
  ],
  "San Juan": [
    "San Juan Capital",
    "Rawson",
    "Chimbas",
    "Rivadavia",
    "Santa Lucía",
    "Caucete",
    "Pocito",
    "Sarmiento",
  ],
  "San Luis": [
    "San Luis Capital",
    "Villa Mercedes",
    "Merlo",
    "Justo Daract",
    "Quines",
  ],
  Catamarca: [
    "San Fernando del Valle de Catamarca",
    "Andalgalá",
    "Belén",
    "Santa María",
    "Tinogasta",
  ],
  "La Rioja": [
    "La Rioja Capital",
    "Chilecito",
    "Aimogasta",
    "Chamical",
    "Villa Unión",
  ],
  Formosa: ["Formosa Capital", "Clorinda", "Pirané", "El Colorado"],
  "La Pampa": [
    "Santa Rosa",
    "General Pico",
    "Toay",
    "Eduardo Castex",
    "Realicó",
  ],
  Chubut: [
    "Rawson",
    "Comodoro Rivadavia",
    "Trelew",
    "Puerto Madryn",
    "Esquel",
    "Rada Tilly",
  ],
  "Santa Cruz": [
    "Río Gallegos",
    "Caleta Olivia",
    "Pico Truncado",
    "El Calafate",
    "Puerto Deseado",
  ],
  "Tierra del Fuego": ["Ushuaia", "Río Grande", "Tolhuin"],
  "Santiago del Estero": [
    "Santiago del Estero Capital",
    "La Banda",
    "Termas de Río Hondo",
    "Añatuya",
    "Frías",
  ],
};

// Helper para obtener localidades de una provincia
export const getLocalidades = (provincia: string): string[] => {
  return LOCALIDADES_POR_PROVINCIA[provincia] ?? [];
};

export const USER_ROLES = [{ value: "admin", label: "Administrador" }];

export const API_URL = import.meta.env.VITE_API_URL || "http://localhost:5000";
